apiVersion: v1
kind: Secret
metadata:
  name: some-users
type: Opaque
data:
  MONGODB_BACKUP_USER: YmFja3Vw
  MONGODB_BACKUP_PASSWORD: YmFja3VwMTIzNDU2
  MONGODB_USER_ADMIN_USER: dXNlckFkbWlu
  MONGODB_USER_ADMIN_PASSWORD: dXNlckFkbWluMTIzNDU2
  MONGODB_CLUSTER_ADMIN_USER: Y2x1c3RlckFkbWlu
  MONGODB_CLUSTER_ADMIN_PASSWORD: Y2x1c3RlckFkbWluMTIzNDU2
  MONGODB_CLUSTER_MONITOR_USER: Y2x1c3Rlck1vbml0b3I=
  MONGODB_CLUSTER_MONITOR_PASSWORD: Y2x1c3Rlck1vbml0b3IxMjM0NTY=
---
apiVersion: v1
kind: Secret
metadata:
  name: gc-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: R09PR0tDT0pOUjQ1NFpNVDJIMllCSEwz
  AWS_SECRET_ACCESS_KEY: eUFPRkhtQ0R1Z0ZSRUFCY2RoNUozeGxiK2YxT2lGQnY0WFVDa1Q5cQ==
