apiVersion: psmdb.percona.com/v1alpha1
kind: PerconaServerMongoDB
metadata:
  name: some-name
spec:
  #platform: openshift
  image:
  imagePullPolicy: Always
  allowUnsafeConfigurations: false
  backup:
    enabled: true
    debug: true
    restartOnFailure: true
    image: perconalab/percona-server-mongodb-operator:0.4.0-backup
    coordinator:
      enableClientsLogging: true
      resources:
        limits:
          cpu: "100m"
          memory: "0.2G"
        requests:
          cpu: "100m"
          memory: "0.1G"
          storage: "1Gi"
      #storageClass: aws-gp2
      affinity:
       antiAffinityTopologyKey: "kubernetes.io/hostname"
    storages:
      gcs-storage:
        type: s3
        s3:
          credentialsSecret: gc-secret
          region: us-east-1
          bucket: operator-testing
          endpointUrl: https://storage.googleapis.com
  mongod:
    net:
      hostPort: 0
      port: 27017
    operationProfiling:
      mode: slowOp
      rateLimit: 1
      slowOpThresholdMs: 100
    security:
      redactClientLogData: false
    setParameter:
      ttlMonitorSleepSecs: 60
      wiredTigerConcurrentReadTransactions: 128
      wiredTigerConcurrentWriteTransactions: 128
    storage:
      engine: wiredTiger
      inMemory:
        engineConfig:
          inMemorySizeRatio: 0.9
      mmapv1:
        nsSize: 16
        smallfiles: false
      wiredTiger:
        collectionConfig:
          blockCompressor: snappy
        engineConfig:
          cacheSizeRatio: 0.5
          directoryForIndexes: false
          journalCompressor: snappy
        indexConfig:
          prefixCompression: true
  replsets:
  - name: rs0
    affinity:
      antiAffinityTopologyKey: none
    resources:
      limits:
        cpu: 500m
        memory: 0.5G
      requests:
        cpu: 100m
        memory: 0.1G
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 1Gi
    size: 3
  secrets:
    key: some-key
    users: some-users
